version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: springboot_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: springbootdb
      POSTGRES_USER: Boni
      POSTGRES_PASSWORD: Boni123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: springboot_pgadmin
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: alenat313@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data: